#!/bin/bash

cmd="$1"
shift

buf="$("$cmd" < "$1")"
for f in "${@:2}"; do
    buf="$(join <(echo "$buf") <("$cmd" < "$f"))"
done

printf "Instance"
for f in "$@"; do
    printf " %s" "$(basename "$f")"
done
printf "\n%s\n" "$buf"
