#!/usr/bin/env python

import sys

if len(sys.argv) == 1:
    inp = sys.stdin.read()
elif len(sys.argv) == 2:
    with open(sys.argv[1]) as f:
        inp = f.read()
else:
    sys.exit('error: only single file is supported')

entries = inp.split('\n\f\n')
for entry in entries[:-1]:
    lines = entry.split('\n')
    problem = lines[0].split()[-1].split('/')[-1]
    print(problem, end=' ')
    for line in lines:
        if line.startswith('c - find entering arc'):
            print('{:.3f}'.format(float(line.split()[6]) / 1000), end=' ')
        elif line.startswith('c - find join node'):
            print('{:.3f}'.format(float(line.split()[6]) / 1000), end=' ')
        elif line.startswith('c - find leaving arc'):
            print('{:.3f}'.format(float(line.split()[6]) / 1000), end=' ')
        elif line.startswith('c - change flows'):
            print('{:.3f}'.format(float(line.split()[5]) / 1000), end=' ')
        elif line.startswith('c - change states'):
            print('{:.3f}'.format(float(line.split()[5]) / 1000), end=' ')
        elif line.startswith('c - update tree'):
            print('{:.3f}'.format(float(line.split()[5]) / 1000), end=' ')
        elif line.startswith('c - update pots'):
            print('{:.3f}'.format(float(line.split()[5]) / 1000), end=' ')
    print()
