#!/usr/bin/env python

import sys

if len(sys.argv) == 1:
    inp = sys.stdin.read()
elif len(sys.argv) == 2:
    with open(sys.argv[1]) as f:
        inp = f.read()
else:
    sys.exit('error: only single file is supported')

entries = inp.split('\n\f\n')
for entry in entries[:-1]:
    lines = entry.split('\n')
    problem = lines[0].split()[-1].split('/')[-1]
    iterations = 'NaN'
    for line in lines:
        if line.startswith('c # iterations'):
            iterations = int(line.split()[4])
            break
        if line.startswith('# iterations'):
            iterations = int(line.split()[2])
            break
    print(problem, iterations)
