#!/usr/bin/env python

import sys

if len(sys.argv) == 1:
    inp = sys.stdin.read()
elif len(sys.argv) == 2:
    with open(sys.argv[1]) as f:
        inp = f.read()
else:
    sys.exit('error: only single file is supported')

entries = inp.split('\n\f\n')
for entry in entries[:-1]:
    lines = entry.split('\n')
    problem = lines[0].split()[-1].split('/')[-1]
    time = 'NaN'
    for line in lines:
        if line.startswith('c Time'):
            time = '{:.3f}'.format(float(line.split()[3]) / 1000)
            break
        if line.startswith('Run NetworkSimplex'):
            time = '{:.3f}'.format(float(line.split()[11][:-1]))
            break
    print(problem, time)
